apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: demo
            - name: POSTGRES_PASSWORD
              value: example
          ports:
            - containerPort: 5432
