server.port: 8081

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/demo
    username: postgres
    password: example
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: postgresql

    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
      javax:
        persistence:
          schema-generation:
            scripts:
              create-target: create.sql
              action: create
            create-source: metadata

  liquibase:
    changeLog: 'classpath:db/changelog/changelog-main.xml'

topic:
  name: payment









